name: Export roadmap

on:
  schedule:
    - cron: "0 0,4,8,12,16,20 * * *" # every 4 hours
  workflow_dispatch:


jobs:
  export:
    name: "Export roadmap"
    runs-on: ubuntu-latest
    steps:
      - name: "📥 Check-out"
        uses: actions/checkout@v4
      - name: "🧰 Install Python"
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: "🧰 Install pipx"
        run: pip install --user pipx
      - name: "🧰 Install Pipenv"
        run: pipx install pipenv
      - name: "🧰 Install dependencies"
        run: pipenv install --deploy
      - name: "🔑 Store host key"
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.GIT_SSH_HOST }} >> ~/.ssh/known_hosts
      - name: "🔑 Store SSH key"
        run: |
          mkdir -p ~/.ssh
          echo -e "${{ secrets.GIT_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
      - name: "🔑 Store config"
        run: |
          echo -e "
          gitRepositoryUrl: \"${{ secrets.GIT_REPOSITORY_URL }}\"
          gitName: \"${{ secrets.GIT_NAME }}\"
          gitEmail: \"${{ secrets.GIT_EMAIL }}\"
          todoistToken: \"${{ secrets.TODOIST_TOKEN }}\"
          todoistProjectId: \"${{ secrets.TODOIST_PROJECT_ID }}\"
          exportPath: \"roadmap.md\"
          commitMessage: \"Update roadmap\"
          " > config.yaml
      - name: "🧾 Export roadmap"
        run: pipenv run python -m todoist_git_sync
